#!/usr/bin/env python3
"""Generate a lightweight table of contents for durable initiative artifacts."""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DEFAULT_INITIATIVES = ROOT / "initiatives"
DEFAULT_OUTPUT = ROOT / "ARTIFACT_INDEX.md"


def _title(path: Path) -> str:
    if path.name.lower() == "readme.md":
        return "Overview"
    stem = path.stem.replace("_", " ").replace("-", " ")
    return " ".join(word.upper() if word.lower().startswith("adr") else word.capitalize() for word in stem.split())


def _jira_key(directory_name: str) -> str:
    match = re.match(r"^([A-Z][A-Z0-9]+-\d+)(?:-|$)", directory_name)
    return match.group(1) if match else directory_name


def discover(initiatives_dir: Path) -> list[tuple[Path, list[Path]]]:
    workspaces: list[tuple[Path, list[Path]]] = []
    if not initiatives_dir.exists():
        return workspaces
    for directory in sorted(path for path in initiatives_dir.iterdir() if path.is_dir() and not path.name.startswith(".")):
        files = sorted(
            path
            for path in directory.rglob("*")
            if path.is_file() and not path.name.startswith(".") and "__pycache__" not in path.parts
        )
        workspaces.append((directory, files))
    return workspaces


def render(initiatives_dir: Path = DEFAULT_INITIATIVES, root: Path = ROOT) -> str:
    lines = [
        "# Artifact Index",
        "",
        "> Generated by `python tools/artifact_index.py --write`. Do not maintain this file by hand.",
        "> Jira remains the source of truth for live status, ownership, priority, releases, and issue relationships.",
        "",
    ]

    workspaces = discover(initiatives_dir)
    if not workspaces:
        lines.extend([
            "No initiative workspaces currently contain durable artifacts.",
            "",
        ])
        return "\n".join(lines)

    for directory, files in workspaces:
        key = _jira_key(directory.name)
        label = directory.name[len(key):].lstrip("-").replace("-", " ").strip()
        heading = f"## {key}" + (f" - {label.title()}" if label else "")
        lines.extend([heading, ""])
        if not files:
            lines.extend(["_No artifacts yet._", ""])
            continue
        for path in files:
            relative = path.relative_to(root).as_posix()
            lines.append(f"- [{_title(path)}]({relative})")
        lines.append("")

    return "\n".join(lines)


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument("--write", action="store_true", help="Write the generated index to ARTIFACT_INDEX.md")
    mode.add_argument("--check", action="store_true", help="Exit non-zero if ARTIFACT_INDEX.md is stale")
    parser.add_argument("--initiatives", type=Path, default=DEFAULT_INITIATIVES)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    return parser


def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    generated = render(args.initiatives, ROOT)

    if args.write:
        args.output.write_text(generated, encoding="utf-8")
        print(f"Wrote {args.output}")
        return 0

    if args.check:
        existing = args.output.read_text(encoding="utf-8") if args.output.exists() else ""
        if existing != generated:
            print("ARTIFACT_INDEX.md is stale. Run: python tools/artifact_index.py --write", file=sys.stderr)
            return 1
        print("ARTIFACT_INDEX.md is current")
        return 0

    print(generated, end="")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
