#!/usr/bin/env python3
"""Keep the mathnasium-product-lifecycle plugin in sync with this repository.

The plugin no longer bundles standards or playbooks: it reads the Technology & Product
Handbook in Confluence live. This tool maintains what is left:

* copies handbook/index.md (the page-ID map) into each skill as ``handbook-index.md``;
* bumps the plugin version in plugin.json whenever any plugin content changes
  (SKILL.md files, the index copies, hooks/), so clients see an update.

    python tools/build_plugin.py           # sync copies, bump version if content changed
    python tools/build_plugin.py --check   # exit non-zero if the plugin folder is stale
"""

from __future__ import annotations

import argparse
import hashlib
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PLUGIN_DIR = ROOT / "plugins" / "mathnasium-product-lifecycle"
SKILLS_DIR = PLUGIN_DIR / "skills"
MANIFEST = PLUGIN_DIR / ".claude-plugin" / "plugin.json"
DIGEST_FILE = PLUGIN_DIR / ".build-digest"
INDEX_SOURCE = ROOT / "handbook" / "index.md"
INDEX_NAME = "handbook-index.md"
SKILLS_WITH_INDEX = ("handbook", "write-jira-story")


def render_index() -> str:
    banner = "<!-- Generated by tools/build_plugin.py from handbook/index.md. Do not edit; change the source and rebuild. -->\n\n"
    return banner + INDEX_SOURCE.read_text(encoding="utf-8")


def index_copies() -> dict[Path, str]:
    content = render_index()
    return {SKILLS_DIR / skill / INDEX_NAME: content for skill in SKILLS_WITH_INDEX}


def _content_files() -> list[Path]:
    files = [path for path in SKILLS_DIR.rglob("*") if path.is_file()]
    hooks = PLUGIN_DIR / "hooks"
    files += [path for path in hooks.rglob("*") if path.is_file() and "__pycache__" not in path.parts] if hooks.exists() else []
    return sorted(files)


def _digest(copies: dict[Path, str]) -> str:
    sha = hashlib.sha256()
    for path in _content_files():
        if path in copies:
            continue
        sha.update(path.relative_to(PLUGIN_DIR).as_posix().encode())
        sha.update(path.read_bytes())
    for path in sorted(copies):
        sha.update(path.relative_to(PLUGIN_DIR).as_posix().encode())
        sha.update(copies[path].encode())
    return sha.hexdigest()


def _bump_patch(version: str) -> str:
    major, minor, patch = (int(part) for part in version.split("."))
    return f"{major}.{minor}.{patch + 1}"


def is_current(copies: dict[Path, str] | None = None) -> bool:
    copies = copies if copies is not None else index_copies()
    for path, content in copies.items():
        if not path.exists() or path.read_text(encoding="utf-8") != content:
            return False
    stored = DIGEST_FILE.read_text(encoding="utf-8").strip() if DIGEST_FILE.exists() else ""
    return stored == _digest(copies)


def build(copies: dict[Path, str] | None = None) -> bool:
    """Write the index copies and bump the plugin version. Returns True when anything changed."""
    copies = copies if copies is not None else index_copies()
    if is_current(copies):
        return False
    for path, content in copies.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
    manifest = json.loads(MANIFEST.read_text(encoding="utf-8"))
    manifest["version"] = _bump_patch(manifest["version"])
    MANIFEST.write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")
    DIGEST_FILE.write_text(_digest(copies) + "\n", encoding="utf-8")
    return True


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--check", action="store_true", help="Exit non-zero if the plugin folder is stale")
    args = parser.parse_args(argv)

    if not INDEX_SOURCE.exists():
        print(f"Missing {INDEX_SOURCE.relative_to(ROOT)}", file=sys.stderr)
        return 2

    if args.check:
        if not is_current():
            print("Plugin is stale. Run: python tools/build_plugin.py", file=sys.stderr)
            return 1
        print("Plugin is current")
        return 0

    changed = build()
    version = json.loads(MANIFEST.read_text(encoding="utf-8"))["version"]
    print(f"Plugin updated to {version}" if changed else f"Plugin already current ({version})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
