#!/usr/bin/env python3
"""Generate the mathnasium-product-lifecycle plugin's references from standards/ and playbooks/.

The plugin's SKILL.md is hand-written. Everything under ``references/`` is generated, so a
rule lives in exactly one file in this repository and the plugin can never drift from it.

    python tools/build_plugin.py           # regenerate references, bump version if content changed
    python tools/build_plugin.py --check   # exit non-zero if the plugin folder is stale
"""

from __future__ import annotations

import argparse
import hashlib
import json
import re
import sys
from pathlib import Path, PurePosixPath

ROOT = Path(__file__).resolve().parents[1]
PLUGIN_DIR = ROOT / "plugins" / "mathnasium-product-lifecycle"
SKILL_DIR = PLUGIN_DIR / "skills" / "write-jira-story"
REFERENCES_DIR = SKILL_DIR / "references"
MANIFEST = PLUGIN_DIR / ".claude-plugin" / "plugin.json"
DIGEST_FILE = PLUGIN_DIR / ".build-digest"

# repo-relative source -> file name inside references/
SOURCES: dict[str, str] = {
    "standards/story.md": "story.md",
    "standards/task.md": "task.md",
    "standards/bug.md": "bug.md",
    "standards/lifecycle.md": "lifecycle.md",
    "standards/jira-conventions.md": "jira-conventions.md",
    "standards/ai-release-confidence.md": "ai-release-confidence.md",
    "playbooks/write-story.md": "write-story.md",
    "playbooks/refine-story.md": "refine-story.md",
    "playbooks/split-story.md": "split-story.md",
    "playbooks/ready-check.md": "ready-check.md",
    "playbooks/review-story.md": "review-story.md",
    "playbooks/cleanup.md": "cleanup.md",
    "templates/story.md": "story-template.md",
}

_LINK = re.compile(r"\[([^\]]+)\]\(([^)\s]+)\)")
_BACKTICK_PATH = re.compile(r"`((?:standards|playbooks|templates)/[A-Za-z0-9_.-]+\.md)(#[A-Za-z0-9_-]+)?`")


def _resolve(source: str, target: str) -> str:
    """Repo-relative path a link target points to, from a given source file."""
    parts: list[str] = []
    for part in (PurePosixPath(source).parent / target).parts:
        if part == "..":
            if parts:
                parts.pop()
        elif part != ".":
            parts.append(part)
    return "/".join(parts)


def rewrite_links(text: str, source: str) -> str:
    """Point repo-relative links at sibling reference files; unwrap links that leave the plugin."""

    def link(match: re.Match[str]) -> str:
        label, target = match.group(1), match.group(2)
        path, _, anchor = target.partition("#")
        if not path or re.match(r"^[a-z]+:", path):
            return match.group(0)
        resolved = _resolve(source, path)
        mapped = SOURCES.get(resolved)
        if mapped:
            return f"[{label}]({mapped}{'#' + anchor if anchor else ''})"
        return label

    def backtick(match: re.Match[str]) -> str:
        mapped = SOURCES.get(match.group(1))
        if not mapped:
            return match.group(0)
        return f"`{mapped}{match.group(2) or ''}`"

    return _BACKTICK_PATH.sub(backtick, _LINK.sub(link, text))


def render_reference(source: str) -> str:
    body = (ROOT / source).read_text(encoding="utf-8")
    banner = f"<!-- Generated by tools/build_plugin.py from {source}. Do not edit; change the source and rebuild. -->\n\n"
    return banner + rewrite_links(body, source)


def generate() -> dict[str, str]:
    return {name: render_reference(source) for source, name in SOURCES.items()}


def _digest(references: dict[str, str]) -> str:
    sha = hashlib.sha256()
    skill = SKILL_DIR / "SKILL.md"
    sha.update(skill.read_bytes() if skill.exists() else b"")
    for name in sorted(references):
        sha.update(name.encode())
        sha.update(references[name].encode())
    return sha.hexdigest()


def _bump_patch(version: str) -> str:
    major, minor, patch = (int(part) for part in version.split("."))
    return f"{major}.{minor}.{patch + 1}"


def _existing_references() -> dict[str, str]:
    if not REFERENCES_DIR.exists():
        return {}
    return {path.name: path.read_text(encoding="utf-8") for path in sorted(REFERENCES_DIR.glob("*.md"))}


def is_current(references: dict[str, str] | None = None) -> bool:
    references = references if references is not None else generate()
    stored = DIGEST_FILE.read_text(encoding="utf-8").strip() if DIGEST_FILE.exists() else ""
    return _existing_references() == references and stored == _digest(references)


def build(references: dict[str, str] | None = None) -> bool:
    """Write references and bump the plugin version. Returns True when anything changed."""
    references = references if references is not None else generate()
    if is_current(references):
        return False
    REFERENCES_DIR.mkdir(parents=True, exist_ok=True)
    for stale in REFERENCES_DIR.glob("*.md"):
        if stale.name not in references:
            stale.unlink()
    for name, content in references.items():
        (REFERENCES_DIR / name).write_text(content, encoding="utf-8")
    manifest = json.loads(MANIFEST.read_text(encoding="utf-8"))
    manifest["version"] = _bump_patch(manifest["version"])
    MANIFEST.write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")
    DIGEST_FILE.write_text(_digest(references) + "\n", encoding="utf-8")
    return True


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--check", action="store_true", help="Exit non-zero if the generated plugin folder is stale")
    args = parser.parse_args(argv)

    missing = [source for source in SOURCES if not (ROOT / source).exists()]
    if missing:
        print(f"Missing source files: {', '.join(missing)}", file=sys.stderr)
        return 2

    if args.check:
        if not is_current():
            print("Plugin is stale. Run: python tools/build_plugin.py", file=sys.stderr)
            return 1
        print("Plugin is current")
        return 0

    changed = build()
    version = json.loads(MANIFEST.read_text(encoding="utf-8"))["version"]
    print(f"Plugin updated to {version}" if changed else f"Plugin already current ({version})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
